name: HTML Validation

on: push

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check hero section
        run: |
          if grep -q '<section class="hero"' index.html; then
            echo "Hero section exists"
          else
            echo "Hero section missing!"
            exit 1
          fi
      - name: Check skills section
        run: |
         if grep -q '<section class="skills"' index.html; then 
            echo "Skills section exists"
          else
            echo "Skills section missing!"
            exit 2
          fi 
      - name: Check newsletter section
        run: |
         if grep -q '<section class="newsletter"' index.html; then 
            echo "Newsletter section exists"
          else
            echo "Newsletters section missing!"
            exit 3
          fi     
      - name: Check JavaScript exists
        run: test -f tooplate-musician-script.js

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check JS syntax
        run: node --check tooplate-musician-script.js